name: GitHub Downloader
# Define when to run job here
on: [push, pull_request]

jobs:
  example_job:
    runs-on: ubuntu-latest
    name: Runing Github Downloader
    steps:
    - name: Build Jekyll site.
    - uses: fabacab/jekyll-builder-for-github-pages-action@v1 # Or whatever "@ref" you want.
